# Generated by Django 3.0.2 on 2020-01-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('heure', models.CharField(max_length=100)),
                ('temp_2m', models.CharField(max_length=100)),
                ('temp_sol', models.CharField(max_length=100)),
                ('temp_850hPa', models.CharField(max_length=100)),
                ('temp_500hPa', models.CharField(max_length=100)),
                ('pression_niveau_de_la_mer', models.CharField(max_length=100)),
                ('pluie_interval_3h', models.CharField(max_length=100)),
                ('pluie_convective_interval_3h', models.CharField(max_length=100)),
                ('humidité_2m', models.CharField(max_length=100)),
                ('vent_moyen_10m', models.CharField(max_length=100)),
                ('vent_rafales_10m', models.CharField(max_length=100)),
                ('vent_direction_10m', models.CharField(max_length=100)),
                ('iSO_zero', models.CharField(max_length=100)),
                ('risque_neige', models.CharField(max_length=100)),
                ('cape', models.CharField(max_length=100)),
                ('nebulosite_haute', models.CharField(max_length=100)),
                ('nebulosite_moyenne', models.CharField(max_length=100)),
                ('nebulosite_basse', models.CharField(max_length=100)),
                ('nebulosite_totale', models.CharField(max_length=100)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='data.Ville')),
            ],
        ),
    ]
